---
title: "Obtención de lluvias para juntar con sismos. Exploración"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Exploración de lluvias mensuales

En primer lugar, se cargan los datos de precipitaciones.
```{r}
# Importar dataset de lluvias mensuales

prAmon <- t(read.csv("https://users.dcc.uchile.cl/~cllull/IntroMineriaDatos/DataSets/cr2_prAmon_2018/cr2_prAmon_2018.txt"))

colnames(prAmon) <- as.character(unlist(prAmon[1, ])) # Le pone nombre a las columnas
prAmon <- prAmon[-1, ] # Extrae los datos
View(prAmon)

prAmon_na <- prAmon # Copia de prAmon
prAmon_na[prAmon == -9999] <- NA # Todas las celdas con -9999 a NA
```

```{r}
prDaily <- t(read.csv("https://users.dcc.uchile.cl/~cllull/IntroMineriaDatos/DataSets/cr2_prDaily_2018/cr2_prDaily_2018.txt"))
colnames(prDaily) <- as.character(unlist(prDaily[1, ])) # Le pone nombre a las columnas
prAmon <- prDaily[-1, ] # Extrae los datos
View(prDaily)

prDaily_na <- prDaily # Copia de prAmon
prDaily_na[prDaily == -9999] <- NA # Todas las celdas con -9999 a NA

prDaily_na <- as.data.frame(prDaily_na)
prDaily_na <- prDaily_na[-c(),]
```

Se debe ajustar a la cantidad de datos que necesitamos, por lo que procederemos a eliminar datos anteriores al año 2008.

```{r}
library(tidyverse)
prDaily_2008 <- prDaily_na %>% select(-("1900-01-01":"2007-12-31")) %>% select(-(institucion:fuente))
prDaily_2008$latitud <- as.numeric(as.character(prDaily_2008$latitud))

View(prDaily_2008)
```

Ahora se debe agregar la columna respectiva a su región, para poder compararla con los otros datasets

```{r}
put_regions <- function(dataFrame) {
  dataFrame$Region_Name <- NA
  dataFrame$Region_Number <- NA
  for (i in 1:nrow(prDaily_2008)) {
    lat= dataFrame[i, "latitud"]
    # Arica parte en -17.4605207
    if (lat > -19.074543) {
      dataFrame[i, "Region_Name"] <- "Región de Arica y Parinacota"
      dataFrame[i, "Region_Number"] <- 15
    }
    else if (lat > -21.4736859) {
      dataFrame[i, "Region_Name"] <- "Región de Tarapacá"
      dataFrame[i, "Region_Number"] <- 1
    }
    else if (lat > -25.877909) {
      dataFrame[i, "Region_Name"] <- "Región de Antofagasta"
      dataFrame[i, "Region_Number"] <- 2
    }
    else if (lat > -29.273360) {
      dataFrame[i, "Region_Name"] <- "Región de Atacama"
      dataFrame[i, "Region_Number"] <- 3
    }
    else if (lat > -32.103216) {
      dataFrame[i, "Region_Name"] <- "Región de Coquimbo"
      dataFrame[i, "Region_Number"] <- 4
    }
    else if (lat > -33.130581) {
      dataFrame[i, "Region_Name"] <- "Región de Valparaíso"
      dataFrame[i, "Region_Number"] <- 5
    }
    else if (lat > -34.070436) {
      dataFrame[i, "Region_Name"] <- "Región Metropolitana de Santiago"
      dataFrame[i, "Region_Number"] <- 13
    }
    else if (lat > -34.821344) {
      dataFrame[i, "Region_Name"] <- "Región del Libertador General Bernardo O’Higgins"
      dataFrame[i, "Region_Number"] <- 6
    }
    else if (lat > -36.276864) {
      dataFrame[i, "Region_Name"] <- "Región del Maule"
      dataFrame[i, "Region_Number"] <- 7
    }
    else if (lat > -36.651832) {
      dataFrame[i, "Region_Name"] <- "Región de Ñuble"
      dataFrame[i, "Region_Number"] <- 16
    }
    else if (lat > -37.833320) {
      dataFrame[i, "Region_Name"] <- "Región del Biobío"
      dataFrame[i, "Region_Number"] <- 8
    }
    else if (lat > -39.455727) {
      dataFrame[i, "Region_Name"] <- "Región de la Araucanía"
      dataFrame[i, "Region_Number"] <- 9
    }
    else if (lat > -40.543828) {
      dataFrame[i, "Region_Name"] <- "Región de Los Ríos"
      dataFrame[i, "Region_Number"] <- 14
    }
    else if (lat > -43.472729) {
      dataFrame[i, "Region_Name"] <- "Región de Los Lagos"
      dataFrame[i, "Region_Number"] <- 10
    }
    else if (lat > -49.098570) {
      dataFrame[i, "Region_Name"] <- "Región de Aysén del General Carlos Ibáñez del Campo"
      dataFrame[i, "Region_Number"] <- 11
    }
    else { # lat > -56.051547
      dataFrame[i, "Region_Name"] <- "Región de Magallanes y de la Antártica Chilena"
      dataFrame[i, "Region_Number"] <- 12
    }
  }
  return(dataFrame)
}
prDaily_2008 <- put_regions(prDaily_2008)

```

```{r}

```

